# Generated by Django 5.1.1 on 2024-09-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.BooleanField(default=True)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('openid', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('is_pay', models.BooleanField(default=False)),
                ('idno', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(blank=True, max_length=50)),
                ('avatar', models.FileField(blank=True, upload_to='avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
