# Generated by Django 5.1.1 on 2024-09-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.BooleanField(default=True)),
                ('openid', models.CharField(blank=True, max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('sp_appid', models.CharField(blank=True, max_length=50)),
                ('sub_appid', models.CharField(blank=True, max_length=50)),
                ('sp_mchid', models.CharField(blank=True, max_length=50)),
                ('sub_mchid', models.CharField(blank=True, max_length=50)),
                ('sp_openid', models.CharField(blank=True, max_length=50)),
                ('sub_openid', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('res_content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
