# Generated by Django 5.1.1 on 2024-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='out_trade_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
