# Generated by Django 5.1.1 on 2024-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_paymentinfo_out_trade_no_paymentinfo_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('valid', models.BooleanField(default=True)),
                ('refund_id', models.CharField(blank=True, max_length=50)),
                ('out_refund_no', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('out_trade_no', models.CharField(blank=True, max_length=50)),
                ('refund', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('sp_mchid', models.CharField(blank=True, max_length=50)),
                ('sub_mchid', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('account', models.CharField(blank=True, max_length=500)),
                ('res_content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
